services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
      - "8020:8020"
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_namenode_rpc_address=namenode:8020
      - HDFS_CONF_dfs_namenode_http_address=namenode:9870
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_permissions=false
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./data:/data:ro

    networks:
      - hadoop-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
      - HDFS_CONF_dfs_permissions=false
    volumes:
      - datanode-data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop-net
volumes:
  namenode-data:
  datanode-data:

networks:
  hadoop-net:
    driver: bridge

